// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgiwtlodhacxqbhzrewe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnaXd0bG9kaGFjeHFiaHpyZXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODM3ODcsImV4cCI6MjA2MjI1OTc4N30.4dSmHd6r7ukXLhKUFYn3awdhTRQ-1A6SW0Ou1PAgob0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);